Public Class Articulo
    Public Property ArtId As Integer
    Public Property ArtTipId As Integer?
    Public Property PrdId As Integer?
    Public Property ArtCatId As Integer?
    Public Property NivId As String
    Public Property MrcId As Integer?
    Public Property ArtClsId As Integer?
    Public Property ArtEnvId As Integer?
    Public Property ArtRepId As Integer?
    Public Property ArtCom As Boolean
    Public Property RubId As Integer
    Public Property MdlId As Integer?
    Public Property ArtDsc As String
    Public Property ArtDscCta As String
    Public Property ArtPerDia As Integer?
    Public Property ArtImg As Byte()
    Public Property ArtOvr As Boolean
    Public Property ArtFra As Boolean
    Public Property ArtVen As Boolean
    Public Property ArtObs As String
    Public Property ArtMer As Decimal?
    Public Property ArtExtVta As Boolean
    Public Property ArtPer As Boolean
    Public Property ArtExp As Boolean
    Public Property ArtSer As Boolean
    Public Property ArtSerOcu As Boolean
    Public Property ArtDiaGtia As Integer
    Public Property ArtAct As Boolean
    Public Property ArtCtrStk As Boolean
    Public Property ArtUPC As String
    Public Property ProvIdCst As Integer?
    Public Property ArtMgr As Decimal?
    Public Property ArtIdAlt As String
    Public Property ArtAudUsrIns As String
    Public Property ArtAudFchIns As DateTime
    Public Property ArtAudUsrUpd As String
    Public Property ArtAudFchUpd As DateTime
    Public Property ArtRid As Integer
    Public Property ArtWeb As Boolean
    Public Property UniId As Integer?
    Public Property ArtShp As Boolean
    Public Property ArtPso As Decimal?
    Public Property ArtLng As Decimal?
    Public Property ArtAnc As Decimal?
    Public Property ArtAlt As Decimal?
    Public Property ArtGiaVar As Boolean
    Public Property ArtIdGia As Integer?
    Public Property ArtDscAtr As String
    Public Property ArtCodExt As String
    Public Property IsDeleted As Boolean
    Public Property CndId As Integer?
    Public Property CsgId As Integer?
    Public Property ArtIdExt As Integer?
End Class
